---

-  hosts: all
   become: true
   tasks:
    - name: copy files to hosts
      copy:
        src: web_page.html
        dest: /var/www/html/index.html
        owner: vboxuser
        group: root
        mode: 0777
    - name: Install unzip
      apt:
        name: unzip
    - name: Download and unzip the website
      unarchive:
        src: https://www.free-css.com/assets/files/free-css-templates/download/page296/finexo.zip
        dest: /home/vboxuser/
        remote_src: yes
        mode: 0755
        owner: root
    - name: host the website
      command:
        cmd: cp -r /home/vboxuser/finexo-html/. /var/www/html

