---

- hosts: all        #You can use group name instead of all to run command on servers inside a particular group
  become: true
  tasks:

  -  name: checking update 
     apt:
      update_cache: yes

  -  name: install apache2 package
     apt:
      name: apache2

  -  name: add php support on hosts
     apt:
      name: libapache2-mod-php
      state: latest

################################################################################################################################

# Using one task to install multiple pacakges

  -  name: install apache2 and php and update the cache
     apt:
       name:
        -  apache2
        -  libapache2-mod-php
       update_cache: yes





