---
-  hosts: all
   become: true
   tasks: 
    - name: Start a service
      service:
        name: apache2
        state: started
     - name: Start a service
       service:
         name: apache2
         state: stopped
      - name: Start a service
        service:
          name: apache2
          state: enabled


